theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: bonnesnotes.org
  search:
    active: true
  posts:
    index:
      layout: grid
  debug:
     productionUrl: "https://www.bonnesnotes.org"